arity_02.p:12: Arity error got 2 values, but 1 values were expected
arity_02.p:13: Arity error got 1 values, but 0 values were expected
arity_02.p:19: Arity error got 0 values, but 1 values were expected
arity_02.p:23: Arity error got 1 values, but 0 values were expected
arity_02.p:28: Arity error got 1 values, but 0 values were expected
arity_02.p:32: Arity error got 1 values, but 0 values were expected
arity_02.p:38: Arity error got 0 values, but 1 values were expected
arity_02.p:42: Arity error got 0 values, but 1 values were expected
