arity.p:14: Arity error got 2 values, but 1 values were expected
arity.p:15: Arity error got 1 values, but 0 values were expected
arity.p:19: Arity error got 1 values, but 0 values were expected
arity.p:24: Arity error got 0 values, but 1 values were expected
arity.p:30: Arity error got 1 values, but 0 values were expected
arity.p:34: Arity error got 1 values, but 0 values were expected
arity.p:40: Arity error got 0 values, but 1 values were expected
arity.p:44: Arity error got 0 values, but 1 values were expected
