ho_7.p:14: One or more resources needed for an argument to a call is not provided in by the passed-in value
ho_7.p:20: One or more resources needed for an argument to a call is not provided in by the passed-in value
ho_7.p:32: One or more resources needed for this call is unavailable in this function
ho_7.p:46: Call uses or observes a resource but has no !
ho_7.p:57: Call has a ! but does not need it
ho_7.p:80: Call uses or observes a resource but has no !
ho_7.p:92: One or more resources needed for this call is unavailable in this function
ho_7.p:113: The function returns a higher order value that uses or observes one or more resources, however the resources arn't declared in the function's return type
