res_1.p:13: Call uses or observes a resource but has no !
res_1.p:14: Call uses or observes a resource but has no !
res_1.p:21: Call has a ! but does not need it
res_1.p:30: One or more resources needed for this call is unavailable in this function
res_1.p:37: One or more resources needed for this call is unavailable in this function
res_1.p:50: One or more resources needed for this call is unavailable in this function
res_1.p:55: One or more resources needed for this call is unavailable in this function
