res_3.p:14: Resource (or related resource) is used multiple times in one statement
res_3.p:18: Resource (or related resource) is used multiple times in one statement
res_3.p:21: Resource (or related resource) is used multiple times in one statement
res_3.p:24: Resource (or related resource) is used multiple times in one statement
res_3.p:27: Resource (or related resource) is used multiple times in one statement
res_3.p:30: Resource (or related resource) is used multiple times in one statement
res_3.p:34: Resource (or related resource) is used multiple times in one statement
