resource_invalid_3.p:15: Statement has more than one ! call
resource_invalid_3.p:19: Statement has more than one ! call
resource_invalid_3.p:22: Statement has more than one ! call
resource_invalid_3.p:25: Statement has more than one ! call
resource_invalid_3.p:28: Statement has more than one ! call
resource_invalid_3.p:31: Statement has more than one ! call
resource_invalid_3.p:35: Statement has more than one ! call
