Type a number of cents to give as change: Trimmed string is: 1234.
Which is the value: $12.34
To give this amount in /perfect/ change you should give:
6 x $2
1 x 20c
1 x 10c
4 x 1c
Type a number of cents to give as change: Trimmed string is: 4321.
Which is the value: $43.21
To give this amount in /perfect/ change you should give:
21 x $2
1 x $1
1 x 20c
1 x 1c
Type a number of cents to give as change: Trimmed string is: 7.
Which is the value: $0.07
To give this amount in /perfect/ change you should give:
1 x 5c
2 x 1c
Type a number of cents to give as change: 
